# tls_server_config:
#   cert_file: desistdaydream.cn.pem
#   key_file: desistdaydream.cn.key

# admin/DesistDaydream
basic_auth_users:
  admin: "$2a$12$B1UftD0BeCRkEfQLT9l1puptvjnMq70eS.beV3vUgIxSNRgmeLMZW"
