name: Container Images Sync
on:
  # 取消 push 的注释后，向本仓库推送代码即可开始 Gitee 同步
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Login to GitHub Package Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: docker build
      # env:
      #   REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      #   REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      run: |
        sudo docker build -f simulate_mysql_exporter/e37_exporter/Dockerfile -t ghcr.io/desistdaydream/e37-exporter:v0.2.0 .
        sudo docker push ghcr.io/desistdaydream/e37-exporter:v0.2.0
