name: Container Images Sync
on:
  push:
    branches:
    - gdas-exporter
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: 登录镜像仓库网站
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    # - name: 为 Docker 提前元数据(tags，labels)
    #   id: meta
    #   uses: docker/metadata-action@v1
    #   with:
    #     images: ghcr.io/desistdaydream/gdas-exporter
    - name: 构建并推送容器镜像
      uses: docker/build-push-action@v2
      with:
        context: .
        file: exporter/gdas_exporter/Dockerfile
        push: true
        tags: ghcr.io/desistdaydream/gdas-exporter
    
    # - name: docker build
    #   env:
    #     REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
    #     REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    #   run: |
    #     echo "${REGISTRY_PASSWORD}" | sudo docker login --username=${REGISTRY_USERNAME} --password-stdin ghcr.io
    #     sudo docker build -f exporter/gdas_exporter/Dockerfile -t ghcr.io/desistdaydream/gdas-exporter:v0.2.0 .
    #     sudo docker push ghcr.io/desistdaydream/gdas-exporter:v0.2.0
